---
title: "PERRY"
author: "Daphné Perry"
format: html
---

```{r}
#| message: false
#| warning: false
library(vroom)
library(ggplot2)
library(knitr)
library(dplyr)
library(here)
library(tidyr)
library(lubridate)
library(readr)
library(tidyverse)
here::i_am("grades.Rproj")
```

# Introduction

## Q1:

```{r}
courses <- vroom(here("data", "courses.csv"))
```

## Q2

```{r}
#| message: false
#| warning: false
courses |>
  arrange(course) |>
  rename(
    "course name" = course,
    "identifier" = course_id,
    "trimester" = trimester,
    "number of exams" = nb_grades 
  ) |>
  kable()
```

## Q3

```{r}
students <- vroom(here("data", "students.csv"))|>
   mutate(
    birth_date = ymd(birth_date),
    sex = factor(sex),
    group = factor(group)
  )
```

In the `students` dataset, the `birth_date` variable is correctly stored as a `Date` object.

## Q4

```{r}
grades <- read_delim(
  "data/grades.csv",
  delim = ";",
  na = "_"
)
```

## Q5

```{r}
students |>
  count(group) |>
  ggplot(aes(x = group, y = n)) +
  geom_col()
```

## Q6

```{r}
students |>
  count(group, sex) |>
  ggplot(aes(x = group, y = n, fill = sex)) +
  geom_col(position = "dodge")
```

## Q7

```{r}
students <- students |>
  mutate(
    age = time_length(today() - birth_date, "year") |> round()
  )

ggplot(students, aes(x = age)) +
  geom_histogram(binwidth = 1)
```

## Q8

```{r}
median_age <- students |> 
  group_by(group) |> 
  summarise(median_age = as.integer(median(age)))

median_age |> 
  kable(col.names = c("Group", "Median age"))
```

## Q9

```{r}
students |>
  arrange(desc(age)) |>
  group_by(group) |>
  slice_max(age, n = 1) |>
  ungroup() |>
  arrange(desc(age)) |>
  select(id, sex, age, group) |>
  kable()
```

## Q10

The data set contains `r grades |> drop_na(grade) |> nrow()` grades.
